Homework hibernate
gujaKhela/SecondLesson pull request #11
Opened 2024-09-26 11:35 UTC by gujaKhela

2024-09-26 13:50 UTC, Alexmansar requested changes
@gujaKhela Hi) In general good job, but I have some general comments. So please fix in all places)

2024-09-26 13:50 UTC, Alexmansar commented on src/main/java/com/example/Ticket.java
>          NullableWarningChecker.check(this);
after NullableWarningChecker.check(this);

2024-09-26 13:50 UTC, Alexmansar commented on src/main/java/com/example/TicketDAO.java
> +    private EntityManagerFactory emf = Persistence.createEntityManagerFactory("my_persistence");
could be final?

2024-09-26 13:50 UTC, Alexmansar commented on src/main/java/com/example/TicketDAO.java
>      }
try to use  try with resources

2024-09-26 16:26 UTC, gujaKhela commented on src/main/java/com/example/Ticket.java
>          NullableWarningChecker.check(this);
i did not get it fully?

2024-09-27 05:46 UTC, Alexmansar requested changes
@gujaKhela Hi)) chech some comments please

2024-09-27 05:46 UTC, Alexmansar commented on pom.xml
> +        </dependency>
why we need it now?

2024-09-27 05:46 UTC, Alexmansar commented on src/main/java/com/example/Ticket.java
>          NullableWarningChecker.check(this);
I mean - first validation, if all OK, than this.creationDate = new Timestamp(System.currentTimeMillis());

2024-09-27 05:46 UTC, Alexmansar commented on src/main/java/com/example/TicketDAO.java
> +        //EntityManager em = emf.createEntityManager();
remove please

2024-09-27 05:46 UTC, Alexmansar commented on src/main/java/com/example/TicketDAO.java
> +            }
Why do we need this block?
I think **{** (21 line) and **}** (24 line) are redundant.

2024-09-27 05:46 UTC, Alexmansar commented on src/main/java/com/example/UserBase.java
> +    // Constructors, Getters, Setters
not needed

2024-09-27 07:08 UTC, Alexmansar approved these changes
@gujaKhela  Could be merged))

2024-09-27 09:03 UTC, merged