Homework oop
gujaKhela/SecondLesson pull request #6
Opened 2024-09-06 20:53 UTC by gujaKhela

2024-09-07 06:51 UTC, Alexmansar requested changes
@gujaKhela Hi, please, check small comments))

2024-09-07 06:51 UTC, Alexmansar commented on src/Admin.java
> +    }
hane check logic expect some boolean value)

2024-09-07 06:51 UTC, Alexmansar commented on src/Client.java
> +    }
and here expect just Ticket)

2024-09-07 06:51 UTC, Alexmansar commented on src/Identifiable.java
> +    }
could be separate class

2024-09-07 06:51 UTC, Alexmansar commented on src/NullableWarning.java
> +}
👍

2024-09-07 06:51 UTC, Alexmansar commented on src/Ticket.java
> +        checkNullableWarnings(); // Check nullable warnings in the constructor
this validation should be begore all this...
in your case - 18 line
And use it in every constructor

2024-09-07 06:51 UTC, Alexmansar commented on src/Identifiable.java
> +    private String id;
make it protected

2024-09-07 06:51 UTC, Alexmansar commented on src/Ticket.java
> +        return "Ticket [ID=" + getId() +
and here will be just id

2024-09-07 06:51 UTC, Alexmansar commented on src/Ticket.java
> +    }
remove it please. Just create 1 class)

2024-09-09 19:54 UTC, gujaKhela commented
resolved the feedback and pushed new commits

2024-09-10 06:48 UTC, Alexmansar approved these changes
@gujaKhela Hi, could be merged

2024-09-10 18:35 UTC, merged